config/routes.rb
Dondecomo::Application.routes.draw do
  get "users/index"

  get "users/show"

  get "users/edit"

  get "users/update"

  get "home/index"
  get "home/tenes_local"
  get "home/ayuda"
  get "home/se_viene"

  resources :actions

  resources :reviews

  resources :internal_messages

  devise_for :users
  resources :users

  resources :medals

  resources :working_days

  resources :places

  resources :foods

  resources :categories

  resources :food_types

   match 'search', :to => 'places#search'
   match 'reviews/:id/vote_up', :to => 'reviews#vote_up'
   match 'reviews/:id/vote_down', :to => 'reviews#vote_down'
   match 'send_message', :to => 'users#send_message'

  root :to => "home#index"

end

app/models/working_day.rb
class WorkingDay < ActiveRecord::Base
end

app/controllers/working_days_controller.rb
class WorkingDaysController < ApplicationController
  # GET /working_days
  # GET /working_days.xml
  def index
    @working_days = WorkingDay.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @working_days }
    end
  end

  # GET /working_days/1
  # GET /working_days/1.xml
  def show
    @working_day = WorkingDay.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @working_day }
    end
  end

  # GET /working_days/new
  # GET /working_days/new.xml
  def new
    @working_day = WorkingDay.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @working_day }
    end
  end

  # GET /working_days/1/edit
  def edit
    @working_day = WorkingDay.find(params[:id])
  end

  # POST /working_days
  # POST /working_days.xml
  def create
    @working_day = WorkingDay.new(params[:working_day])

    respond_to do |format|
      if @working_day.save
        format.html { redirect_to(@working_day, :notice => 'Working day was successfully created.') }
        format.xml  { render :xml => @working_day, :status => :created, :location => @working_day }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @working_day.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /working_days/1
  # PUT /working_days/1.xml
  def update
    @working_day = WorkingDay.find(params[:id])

    respond_to do |format|
      if @working_day.update_attributes(params[:working_day])
        format.html { redirect_to(@working_day, :notice => 'Working day was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @working_day.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /working_days/1
  # DELETE /working_days/1.xml
  def destroy
    @working_day = WorkingDay.find(params[:id])
    @working_day.destroy

    respond_to do |format|
      format.html { redirect_to(working_days_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/working_days_helper.rb
module WorkingDaysHelper
end

app/views/working_days/_form.html.erb
<%= form_for(@working_day) do |f| %>
  <% if @working_day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@working_day.errors.count, "error") %> prohibited this working_day from being saved:</h2>

      <ul>
      <% @working_day.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/working_days/edit.html.erb
<h1>Editing working_day</h1>

<%= render 'form' %>

<%= link_to 'Show', @working_day %> |
<%= link_to 'Back', working_days_path %>

app/views/working_days/index.html.erb
<h1>Listing working_days</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @working_days.each do |working_day| %>
  <tr>
    <td><%= working_day.name %></td>
    <td><%= link_to 'Show', working_day %></td>
    <td><%= link_to 'Edit', edit_working_day_path(working_day) %></td>
    <td><%= link_to 'Destroy', working_day, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Working day', new_working_day_path %>

app/views/working_days/new.html.erb
<h1>New working_day</h1>

<%= render 'form' %>

<%= link_to 'Back', working_days_path %>

app/views/working_days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @working_day.name %>
</p>


<%= link_to 'Edit', edit_working_day_path(@working_day) %> |
<%= link_to 'Back', working_days_path %>