config/routes.rb
Dondecomo::Application.routes.draw do
  get "users/index"

  get "users/show"

  get "users/edit"

  get "users/update"

  get "home/index"
  get "home/tenes_local"
  get "home/ayuda"
  get "home/se_viene"

  resources :actions

  resources :reviews

  resources :internal_messages

  devise_for :users
  resources :users

  resources :medals

  resources :working_days

  resources :places

  resources :foods

  resources :categories

  resources :food_types

   match 'search', :to => 'places#search'
   match 'reviews/:id/vote_up', :to => 'reviews#vote_up'
   match 'reviews/:id/vote_down', :to => 'reviews#vote_down'
   match 'send_message', :to => 'users#send_message'

  root :to => "home#index"

end

app/models/internal_message.rb
class InternalMessage < ActiveRecord::Base
end

app/controllers/internal_messages_controller.rb
class InternalMessagesController < ApplicationController
  # GET /internal_messages
  # GET /internal_messages.xml
  def index
    @internal_messages = InternalMessage.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @internal_messages }
    end
  end

  # GET /internal_messages/1
  # GET /internal_messages/1.xml
  def show
    @internal_message = InternalMessage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @internal_message }
    end
  end

  # GET /internal_messages/new
  # GET /internal_messages/new.xml
  def new
    @internal_message = InternalMessage.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @internal_message }
    end
  end

  # GET /internal_messages/1/edit
  def edit
    @internal_message = InternalMessage.find(params[:id])
  end

  # POST /internal_messages
  # POST /internal_messages.xml
  def create
    @internal_message = InternalMessage.new(params[:internal_message])

    respond_to do |format|
      if @internal_message.save
        format.html { redirect_to(@internal_message, :notice => 'Internal message was successfully created.') }
        format.xml  { render :xml => @internal_message, :status => :created, :location => @internal_message }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @internal_message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /internal_messages/1
  # PUT /internal_messages/1.xml
  def update
    @internal_message = InternalMessage.find(params[:id])

    respond_to do |format|
      if @internal_message.update_attributes(params[:internal_message])
        format.html { redirect_to(@internal_message, :notice => 'Internal message was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @internal_message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /internal_messages/1
  # DELETE /internal_messages/1.xml
  def destroy
    @internal_message = InternalMessage.find(params[:id])
    @internal_message.destroy

    respond_to do |format|
      format.html { redirect_to(internal_messages_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/internal_messages_helper.rb
module InternalMessagesHelper
end

app/views/internal_messages/_form.html.erb
<%= form_for(@internal_message) do |f| %>
  <% if @internal_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@internal_message.errors.count, "error") %> prohibited this internal_message from being saved:</h2>

      <ul>
      <% @internal_message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :target_user_id %><br />
    <%= f.text_field :target_user_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/internal_messages/edit.html.erb
<h1>Editing internal_message</h1>

<%= render 'form' %>

<%= link_to 'Show', @internal_message %> |
<%= link_to 'Back', internal_messages_path %>

app/views/internal_messages/index.html.erb
<h1>Listing internal_messages</h1>

<table>
  <tr>
    <th>Subject</th>
    <th>Target user</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @internal_messages.each do |internal_message| %>
  <tr>
    <td><%= internal_message.subject %></td>
    <td><%= internal_message.target_user_id %></td>
    <td><%= internal_message.body %></td>
    <td><%= link_to 'Show', internal_message %></td>
    <td><%= link_to 'Edit', edit_internal_message_path(internal_message) %></td>
    <td><%= link_to 'Destroy', internal_message, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Internal message', new_internal_message_path %>

app/views/internal_messages/new.html.erb
<h1>New internal_message</h1>

<%= render 'form' %>

<%= link_to 'Back', internal_messages_path %>

app/views/internal_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subject:</b>
  <%= @internal_message.subject %>
</p>

<p>
  <b>Target user:</b>
  <%= @internal_message.target_user_id %>
</p>

<p>
  <b>Body:</b>
  <%= @internal_message.body %>
</p>


<%= link_to 'Edit', edit_internal_message_path(@internal_message) %> |
<%= link_to 'Back', internal_messages_path %>