config/routes.rb
Dondecomo::Application.routes.draw do
  get "users/index"

  get "users/show"

  get "users/edit"

  get "users/update"

  get "home/index"
  get "home/tenes_local"
  get "home/ayuda"
  get "home/se_viene"

  resources :actions

  resources :reviews

  resources :internal_messages

  devise_for :users
  resources :users

  resources :medals

  resources :working_days

  resources :places

  resources :foods

  resources :categories

  resources :food_types

   match 'search', :to => 'places#search'
   match 'reviews/:id/vote_up', :to => 'reviews#vote_up'
   match 'reviews/:id/vote_down', :to => 'reviews#vote_down'
   match 'send_message', :to => 'users#send_message'

  root :to => "home#index"

end

app/models/place.rb
class Place < ActiveRecord::Base
	has_attached_file :photo, :styles => {:medium => "300x300>", :thumb => "100x100>"}

	validates :name , :presence => true
	has_and_belongs_to_many :working_days
	has_many :reviews, :order => "votes DESC"
	self.per_page = 5

	#has_many :food_types

	def average_points *options 
		total_points = 0
		total_reviews = Array.new
		if options.count > 0
			if options.first == :masc
				total_reviews = reviews.select do |r|
					r.owner.sex == "M"
				end
			end
			if options.first == :fem
				total_reviews = reviews.select do |r|
					r.owner.sex == "F"
				end
			end

			if options.first == :age
				opt = options.last.to_s
				opts = opt.split("_")

				case opts.first
				when "less"
					total_reviews = reviews.select do |r|
						r.owner.age < Integer(opts.last)
					end
				when "between"
					total_reviews = reviews.select do |r|
						age = r.owner.age
						age <= Integer(opts.last) && age >= Integer(opts[1])
					end
				when "more"
					total_reviews = reviews.select do |r|
						r.owner.age > Integer(opts.last)
					end
				end
			end
		else
			total_reviews = reviews
		end

		total_reviews.each do |r|
			total_points += r.points
		end

		if total_reviews.length == 0
			return 0
		else
			return total_points / total_reviews.length
		end
	end

	def most_voted_review
		reviews.first	
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  before_filter :authenticate_user!, :except => [:search, :show]
  before_filter :check_points, :only => [:edit]

	def check_points
		if !current_user.nil? && current_user.can_edit_place?
			return true
		else
			flash[:error] = "Necesitas 100 puntos para poder editar locales comerciales"
			redirect_to request.referer
			return false
		end
	end
  # GET /places
  # GET /places.xml
  def index
    @places = Place.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @places }
    end
  end

  # GET /places/1
  # GET /places/1.xml
  def show
	@meta[:title] = "DondeVoyAComer.com | Detalles del local de comida"
    @place = Place.find(params[:id])
	@review = Review.new
	@review.place_id = @place.id
	@review.owner_user_id = current_user.id if !current_user.nil?

	

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @place }
    end
  end

  # GET /places/new
  # GET /places/new.xml
  def new
	@meta[:title] = "DondeVoyAComer.com | Ingresar nuevo local de comida"
	  @current_page = "add"
    @place = Place.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @place }
    end
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
  end

  # POST /places
  # POST /places.xml
  def create
    @place = Place.new(params[:place])
	@place.active = true

    respond_to do |format|
      if @place.save
		current_user.points += APP_CONFIG['new_place']
		current_user.save

		act = Action.new({:owner_user_id => current_user.id, :code => :new_place})
		act.set_attributes({:place => @place})
		act.save


        format.html { redirect_to(@place, :notice => 'El local fue creado correctamente!') }
        format.xml  { render :xml => @place, :status => :created, :location => @place }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @place.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.xml
  def update
    @place = Place.find(params[:id])

    respond_to do |format|
	  if !params[:working_days_names].nil?
		params[:place][:working_days] = Array.new
		params[:working_days_names].each do |wdn|
			params[:place][:working_days] << WorkingDay.find_by_name(wdn)
		end
	  end
      if @place.update_attributes(params[:place])
        format.html { redirect_to(@place, :notice => 'El local fue editado correctamente!') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @place.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.xml
  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to(places_url) }
      format.xml  { head :ok }
    end
  end


  def search
	  @meta[:title] = "DondeVoyAComer.com | Busqueda de locales de comida"
	  @current_page = "search"
	  @search_params = params;
	  conditions = Array.new


	  if !params[:category].nil?
		#conditions << ["category_id = ?", Integer(params[:category])]
	  end

	  if !params[:place_type].blank?
		  conditions << ["place_type = ?", params[:place_type]]
	  end

	  if !params[:name].blank?
		  conditions << ["places.name like ?", "%#{params[:name]}%"]
	  end

	  if !params[:highlighted_food].blank?
		  conditions << ["highlited_food like ?", "%#{params[:highlighted_food]}%"]
	  end

	  if !params[:start_time].blank?
		  conditions << ["time(opening_time) <= ?", "#{params[:start_time]}:00"]
		  conditions << ["time(closing_time) >= ?", "#{params[:start_time]}:00"]
	  end

	  if conditions.length > 0
		  #Obtenemos todos los primeros elementos de los arrays y los joineamos en un solo string
		  all_conditions = conditions.map { |c|
			  c.first
		  }.join(" AND ")
		
		  #Obtenemos los segundos elementos de los arrays y lo dejamos como array
		  all_values = conditions.map { |c|
			  c[1..-1]
		  }

		  #Sumamos en un array, el string y todos los valores en formato array
		  conditions = [all_conditions] + all_values
	  end

	  @results = Place.where(conditions).paginate(:page => params[:page])

	  if !params[:working_days_names].nil?
		  @results = @results.joins("join places_working_days on places.id = places_working_days.place_id").joins("join working_days on working_days.id = places_working_days.working_day_id").where(:working_days => {:short_name => params[:working_days_names]}).group("places.id")
	  end


  end
end

app/helpers/places_helper.rb
module PlacesHelper

	def get_place_type_text value
		names = {:bar => "Bar", :rest => "Restaurante", :piza => "Pizzeria",:fast => "Comida rapida", :car => "Carrito", :heladeria => "Heladeria"}
		names[value.to_sym]
	end
end

app/views/places/_form.html.erb
<%= form_for(@place,:html => {:multipart => true, :id => "new-place-form"}) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2>Hubo error(es) al intentar guardar el local:</h2>
	
      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t :name %><br />
    <%= f.text_field :name, {:title => "Nombre del local comercial, ej: La Pasiva, McDonald's, etc"} %>
  </div>
 <div class="field">
    <%= f.label t :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="field" id="address-cont">
    <%= f.label t :address %><br />
    <%= f.text_field :address %>
  </div>
	<div class="field" id="map_canvas">
    </div>

  <div class="field">
		<%= f.label t ('activerecord.attributes.place.working_days') %><br />
		<% WorkingDay.all.each do |d| %>
			<label><%= check_box_tag "working_days_names[]", d.name, @place.working_days.include?(d),{:class => "chkbox"}  %> <%=d.name.html_safe%></label>
		<% end %>
  </div>

<%= f.hidden_field :lng %>
<%= f.hidden_field :lat %>
  <div class="field">
    <%= f.label t :opening_time %><br />
    <%= f.time_select :opening_time, {:minute_step => 15} %>
  </div>
  <div class="field">
    <%= f.label t :closing_time %><br />
    <%= f.time_select :closing_time , {:minute_step => 15}%>
  </div>
  <div class="field">
    <%= f.label t :photo %><br />
    <%= f.file_field :photo%>
  </div>
  <div class="field">
    <%= f.label t ('activerecord.attributes.place.place_type') %><br />
	<%= places_types_dropdown @place.place_type%>
  </div>
  <div class="field">
    <%= f.label t ('activerecord.attributes.place.highlited_food') %><br />
	<%= f.text_field :highlited_food %>
	<span class="form-help-text">Lista de comidas separada por coma (ej: panchos, minutas, pastas)</span>
  </div>
  

  <div class="actions">
    <%= f.submit "Guardar" %>
    <%#= link_to "","",:class => "guardar-btn" %>
  </div>
<div class="clearfix"></div>
<% end %>
<script type="text/javascript">
	initializeGeoCoding();
</script>

app/views/places/_place_box.html.erb
<div class="place-box grid_12">
	<div class="grid_2 place_photo ">
		<%=image_tag place.photo.url(:thumb) %>
	</div> 
	<div class="grid_9 data-block">
		<div class="name"><%=link_to place.name, place%></div>
		<div class="ratting"><b>Puntaje:</b> <%=place.average_points%></div>
		<div class="address"><%=place.address%></div>
		<div class="phone_number">Tel. <%=show_or_default place.phone_number%></div>
	</div>
</div>
<div class="clear"></div>

app/views/places/_search_form.erb
<%
if @search_params.nil?
	@search_params = Hash.new
end
%>

<div class="grid_11 prefix_1">
<div class="grid_10  home-box search-box">
		<h2>
			Buscar dónde comer...
			<% if !@results.nil? %>
			<span class="small"><%=@results.total_entries%> resultado(s) encontrado(s)</span>
			<a href="#">(buscar de nuevo)</a>
			<% end  %>
		</h2>
		<span >
			<div class="help-text ">
				Encontrá los mejores sitios donde comer usando este cuadro de búsqueda.
				<br/>
				Ningún dato es obligatorio, ingresá la información que creas necesaria, solo recuerda que mientras más información ingreses
				mejores serán los resultados encontrados.
			</div >
			<%=form_tag( "search", :method => 'get') do  %>
			<div class="prefix_1 grid_5">
				<div class="field">
					<label for="address">Comer cerca de... (Pr&oacute;ximamente)</label>
					<%=text_field_tag "address", @search_params[:address], {:disabled => true, :title => "Ingresá la dirección para buscar en los alrededores", :class => "text-input"} %>
				</div>
				<div class="field">
					<label for="name">Nombre del local </label>
					<%=text_field_tag "name", @search_params[:name],{:title => "Ingresá el nombre del local (ej. La Pasiva)", :class => "text-input"} %>
				</div>

				<div class="field">
					<label for="highlighted_food">Comida</label>
					<%=text_field_tag "highlighted_food", @search_params[:highlighted_food], {:title => "Esribí lo que tenés ganas de comer (ej. pizza, panchos)", :class => "text-input"} %>
				</div>
			</div>

			<!--
			<div class="field">
				<label for="category">Categoría</label>
				<%=select_tag "category", options_from_collection_for_select(Category.all(:order => :name),"id", "name")%>
			</div>
   -->
			<div class="prefix_1 grid_5">
				<div class="field">
					<label for="place_type">¿Qué estás buscando?</label>
					<%=places_types_dropdown(@search_params[:place_type], "place_type")%>
				</div>
				<div class="field">
					<label >¿Cuándo querés ir?</label>
					<% WorkingDay.all.each do |d| %>
						<% 
						if @search_params[:working_days_names].nil?
							checked = false
						else 
							checked = @search_params[:working_days_names].include?(d.short_name)
						end %>
						<label><%= check_box_tag "working_days_names[]", d.short_name, checked %> <%=d.name.html_safe%></label>
					<% end %>
				</div>

				<div class="field">
					<label >¿A qué hora?</label>
					<%=text_field_tag "start_time",@search_params[:start_time], {:class => "time-picker"} %>
				</div>
			</div>
   <!--
				<div class="grid_1 prefix_10">
					<%=link_to "", "", :class => "search-btn" %>
				</div>
-->
   <!---->
				<div class="grid_1 prefix_10">
					<%=submit_tag "Buscar &#10162;".html_safe, {:class => "search-btn"} %>
				</div>
   <!---->
			<% end %>
		</span>
	</div>
	</div>
<% if !@results.nil? %> 
<script type="text/javascript">
	$(".home-box.search-box").animate({height:"30px", minHeight:"30px"});
	$(".home-box.search-box").children().not("h2").hide();
</script>
<% end %>

app/views/places/edit.html.erb
<div class="home-box">
<h2>Editar Local</h2>
<span>
<%= render 'form' %>

<%#= link_to 'Show', @place %> |
<%#= link_to 'Back', places_path %>
</span>
</div>

app/views/places/index.html.erb
<h1>Listing places</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Active</th>
    <th>Phone number</th>
    <th>Address</th>
    <th>Opening time</th>
    <th>Closing time</th>
    <th>Picture path</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @places.each do |place| %>
  <tr>
    <td><%= place.name %></td>
    <td><%= place.active %></td>
    <td><%= place.phone_number %></td>
    <td><%= place.address %></td>
    <td><%= place.opening_time %></td>
    <td><%= place.closing_time %></td>
    <td><%= image_tag place.photo.url(:thumb) %></td>
    <td><%= get_place_type_text place.place_type %></td>
    <td><%= link_to 'Show', place %></td>
    <td><%= link_to 'Edit', edit_place_path(place) %></td>
    <td><%= link_to 'Destroy', place, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<div class="home-box">
<h2>Nuevo <%=t('activerecord.models.place')%></h2>
<span>

<%= render 'form' %>
	</span>
</div>

app/views/places/search.html.erb
<%=render 'places/search_form' %>
<div class="grid_11 prefix_1">
	<div class="grid_10">
		<div class="results-view home-box">
			<h2>Resultados de la búsqueda</h2>
			<% if @results.total_entries > 0 %>
			<ul>
			<% @results.each do |r| %>
				<li class="<%=cycle("odd","even")%>"><%=render :partial => 'places/place_box', :locals => {:place => r}%></li>
			<% end %>
			</ul>

			<%=will_paginate @results %>
			<% else %>
			<div class="notification alert" style="display:block;" >No hay resultados para tu búsqueda, intent&aacute; usar el formulario de arriba para refinar tu b&uacute;squeda...</b></div>
			<% end %>
			</div>
		</div>
		</div>

app/views/places/show.html.erb
<div class="grid_10 prefix_1 show-page">
	<div class="grid_8">
		<div class="ficha-local">
			<div class="grid_2 photo_box">
				<%= image_tag @place.photo.url(:thumb) %>
			</div>
			<div class="datos-local grid_8">
				<h2>
  					<%= show_or_default @place.name %>
					<%=link_to "(Editar)", edit_place_path(@place)%>
				</h2>
				<div class="small-data important">
					<b>Puntaje: </b><%= @place.average_points%> / 5 - <a href="#detalles" title="Detalles de la puntuación" class="detalles_puntuacion" id="<%= @place.id %>" >Detalles</a>
					<div style="display:none;">
					<div class="detalles_puntuacion" id="detalles">
						<h3>Discriminado por sexo</h3>
						<p>
							<b>Promedio masculino:</b> <%=@place.average_points :masc%><br/>
							<b>Promedio femenino:</b> <%=@place.average_points :fem %><br/>
						</p>
						<h3>Discriminado por edades</h3>
						<p>
							<b>Menores de 15 a&ntilde;os:</b> <%=@place.average_points :age, :less_15%><br/>
							<b>Entre 15 y 25 a&ntilde;os:</b> <%=@place.average_points :age, :between_15_25%><br/>
							<b>Entre 25 y 50 a&ntilde;os:</b> <%=@place.average_points :age, :between_25_50%><br/>
							<b>Entre 50 y 65 a&ntilde;os:</b> <%=@place.average_points :age, :between_50_65%><br/>
							<b>Mayor de 65 a&ntilde;os:</b> <%=@place.average_points :age, :more_65%><br/>
						</p>

					</div>
						</div>
				</div>

				<div class="small-data">
  					<%= show_or_default @place.address%>
				</div>
				<div class="small-data">
  					Tel.: <%= show_or_default @place.phone_number%>
				</div>
				<div class="small-data">
  					<b>Atención al público</b>
					<% if !@place.working_days.nil? && @place.working_days.length > 0 %>
						<% 
						days = @place.working_days.map { |w| 
							w.short_name 
						}.join(" - ")%>
					<%=show_or_default days%>
					<% end %>
					<br/>
					Desde las <%= show_or_default(@place.opening_time) %> a las  <%= show_or_default(@place.closing_time) %>
				</div>
				<div class="small-data">
  					Comidas destacadas: <%= show_or_default @place.highlited_food%>
				</div>
			</div>
			<div class="clear"></div>
		</div>
		<div class="listado-comentarios">
			<%=render :file => 'reviews/index', :locals => {:reviews => @place.reviews } %>
		</div>
	</div>
	<div class="grid_4">
		<div id="map_canvas">

		</div>
		<script type="text/javascript">
			plotCoords(<%=@place.lat%>, <%=@place.lng%>);
		</script>
		
	<div class="puntaje">
	<!--	Puntaje: <%=@place.average_points%>-->
	</div>
<div class="home-box">
	<h2>Comentario destacado</h2>
	<% if @place.reviews.length > 0 %>
	<% best_review = @place.reviews.first%>
		<span class="review-box">
			<div class="review-header">
				Comentario de: 
				<%= best_review.owner.get_fullname%>	
				(<%=best_review.points%> / 5)
			</div>
			<div class="review-body">
				<%= best_review.body%>	
			</div>
			<div class="review-owner">
			</div>

		</span>
	<% else %>
	<span class="notice">
		No hay ningún comentario destacado aún.<br/>
		¡Vota por uno de ellos para que aparezca aquí!
	</span>
	<% end %>
</div>
	</div>

</div>